local Rebirths = {
	[1] = {
		Unlocks = {
			Multiplier = 0.5,
			Money = 5000,
			Time = 10,
			Floor = 2
		},
		
		Requirements = {
			Money = 1000000,
			Things = {
				"Wolfpaq",
				"Qwelver"
			}
		}
	},
	
	[2] = {
		Unlocks = {
			Multiplier = 1,
			Money = 10000,
			Time = 10,
			Floor = 2
		},

		Requirements = {
			Money = 3000000,
			Things = {
				"NewFissy",
				"Taymaster"
			}
		}
	},
	
	[3] = {
		Unlocks = {
			Multiplier = 2,
			Money = 25000,
			Time = 10,
			Floor = 2
		},

		Requirements = {
			Money = 12500000,
			Things = {
				"Fierzaa",
				"Defaultio"
			}
		}
	},
	
	[4] = {
		Unlocks = {
			Multiplier = 3,
			Money = 50000,
			Time = 10,
			Floor = 2
		},

		Requirements = {
			Money = 35000000,
			Things = {
				"SnickTrix",
				"LostInfinity"
			}
		}
	},
	
	[5] = {
		Unlocks = {
			Multiplier = 4,
			Money = 100000,
			Time = 10,
			Floor = 2
		},

		Requirements = {
			Money = 100000000,
			Things = {
				"Nosniy",
				"Chillthrill709"
				
			}
		}
	},

	[6] = {
		Unlocks = {
			Multiplier = 5,
			Money = 250000,
			Time = 10,
			Floor = 2
		},

		Requirements = {
			Money = 350000000,
			Things = {
				"Dued1"
			}
		}
	},

	[7] = {
		Unlocks = {
			Multiplier = 6,
			Money = 500000,
			Time = 10,
			Floor = 2
		},

		Requirements = {
			Money = 1000000000,
			Things = {
				"YGvw_Sol"
			}
		}
	},

	[8] = {
		Unlocks = {
			Multiplier = 7,
			Money = 1000000,
			Time = 10,
			Floor = 2
		},

		Requirements = {
			Money = 5000000000,
			Things = {
				"Aesthetical"
			}
		}
	},

	[9] = {
		Unlocks = {
			Multiplier = 8,
			Money = 5000000,
			Time = 10,
			Floor = 3
		},

		Requirements = {
			Money = 25000000000,
			Things = {
				"0_0"
			}
		}
	},

	[10] = {
		Unlocks = {
			Multiplier = 9,
			Money = 25000000,
			Time = 10,
			Floor = 3
		},

		Requirements = {
			Money = 250000000000,
			Things = {
				"DJMonopoli"
			}
		}
	},

	[11] = {
		Unlocks = {
			Multiplier = 10,
			Money = 100000000,
			Time = 10,
			Floor = 3
		},

		Requirements = {
			Money = 500000000000,
			Things = {
				"Nikilis"
			}
		}
	},

	[12] = {
		Unlocks = {
			Multiplier = 11,
			Money = 500000000,
			Time = 10,
			Floor = 3
		},

		Requirements = {
			Money = 1000000000000,
			Things = {
				"Asimo3089"
			}
		}
	},

	[13] = {
		Unlocks = {
			Multiplier = 12,
			Money = 1000000000,
			Time = 10,
			Floor = 3
		},

		Requirements = {
			Money = 10000000000000,
			Things = {
				"BelowNatural"
			}
		}
	},

	[14] = {
		Unlocks = {
			Multiplier = 13,
			Money = 1000000000000,
			Time = 10,
			Floor = 3
		},

		Requirements = {
			Money = 50000000000000,
			Things = {
				"No1_Preston"
			}
		}
	},

	[15] = {
		Unlocks = {
			Multiplier = 14,
			Money = 5000000000000,
			Time = 10,
			Floor = 3
		},

		Requirements = {
			Money = 100000000000000,
			Things = {
				"Cracky4"
			}
		}
	},

	[16] = {
		Unlocks = {
			Multiplier = 15,
			Money = 25000000000000,
			Time = 10,
			Floor = 3
		},

		Requirements = {
			Money = 500000000000000,
			Things = {
				"Mygame43"
			}
		}
	},

	[17] = {
		Unlocks = {
			Multiplier = 16,
			Money = 50000000000000,
			Time = 10,
			Floor = 3
		},

		Requirements = {
			Money = 1000000000000000,
			Things = {
				"Rip_indra"
			}
		}
	},

	[18] = {
		Unlocks = {
			Multiplier = 17,
			Money = 100000000000000,
			Time = 10,
			Floor = 3
		},

		Requirements = {
			Money = 10000000000000000,
			Things = {
				"Lightning_Splash"
			}
		}
	}

}

return Rebirths