local ServerLuck = {
	[2] = {
		Time = 900,
		Price = 249,
		DeveloperProductId = 3453058958
	},
	
	[4] = {
		Time = 900,
		Price = 999,
		DeveloperProductId = 3453059253
	},
	
	[6] = {
		Time = 900,
		Price = 1999,
		DeveloperProductId = 3453059969
	},
	
	[8] = {
		Time = 900,
		Price = 3499,
		DeveloperProductId = 3453060901
	},
	
	[10] = {
		Time = 900,
		Price = 4999,
		DeveloperProductId = 3453062306
	}
}

return ServerLuck