local Things = {
	Rate = 2.5,
	Speed = 10,
	StealSpeed = 20,
	
	Things = {
		["Onett"] = {
			Rarity = "Common",
			Price = 0,
			MoneyPerSecond = 1,
			
			Icon = "rbxassetid://123540562500547",

			IdleAnimation = "rbxassetid://507766666",
			WalkAnimation = "rbxassetid://507777826",
			CarryAnimation = "rbxassetid://96104234604417",
			
			Sound = "rbxassetid://112098551161262"
		},
		
		["Wolfpaq"] = {
			Rarity = "Common",
			Price = 100,
			MoneyPerSecond = 2,

			Icon = "rbxassetid://74286261059838",

			IdleAnimation = "rbxassetid://507766666",
			WalkAnimation = "rbxassetid://507777826",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://94160563540782"
		},
		
		["Wildes"] = {
			Rarity = "Common",
			Price = 300,
			MoneyPerSecond = 4,

			Icon = "",

			IdleAnimation = "rbxassetid://507766666",
			WalkAnimation = "rbxassetid://507777826",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://96586692924354"
		},
		
		["Hytok0"] = {
			Rarity = "Common",
			Price = 500,
			MoneyPerSecond = 5,

			Icon = "rbxassetid://81134244537973",

			IdleAnimation = "rbxassetid://507766666",
			WalkAnimation = "rbxassetid://507777826",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://114260179617432"
		},
		
		["Cowoika"] = {
			Rarity = "Common",
			Price = 750,
			MoneyPerSecond = 7,

			Icon = "rbxassetid://76881061857199",

			IdleAnimation = "rbxassetid://507766666",
			WalkAnimation = "rbxassetid://507777826",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://140410674883583"
		},
		
		["Qwelver"] = {
			Rarity = "Common",
			Price = 1000,
			MoneyPerSecond = 10,

			Icon = "rbxassetid://79056755433395",

			IdleAnimation = "rbxassetid://16738333868",
			WalkAnimation = "rbxassetid://16738340646",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://138042499021567"
		},
		
		["Gigi_DTI"] = {
			Rarity = "Common",
			Price = 1500,
			MoneyPerSecond = 13,

			Icon = "rbxassetid://140716572159196",

			IdleAnimation = "rbxassetid://16738333868",
			WalkAnimation = "rbxassetid://16738340646",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://105001126250191"
		},
		
		["NewFissy"] = {
			Rarity = "Rare",
			Price = 2000,
			MoneyPerSecond = 15,

			Icon = "rbxassetid://107839399971026",

			IdleAnimation = "rbxassetid://507766666",
			WalkAnimation = "rbxassetid://507777826",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://71979157870869"
		},
		
		["AlsoNot_Tze"] = {
			Rarity = "Rare",
			Price = 3000,
			MoneyPerSecond = 20,

			Icon = "",

			IdleAnimation = "rbxassetid://507766666",
			WalkAnimation = "rbxassetid://507777826",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://129380754378574"
		},
		
		["WoozyNate"] = {
			Rarity = "Rare",
			Price = 4000,
			MoneyPerSecond = 30,

			Icon = "rbxassetid://121792049170882",

			IdleAnimation = "rbxassetid://122257458498464",
			WalkAnimation = "rbxassetid://782843345",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://91620080777182"
		},
		
		["Coeptus"] = {
			Rarity = "Rare",
			Price = 5000,
			MoneyPerSecond = 40,

			Icon = "rbxassetid://117020969185292",

			IdleAnimation = "rbxassetid://507766666",
			WalkAnimation = "rbxassetid://845386501",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://76732408386498"
		},
		
		["22freshfrenchfries"] = {
			Rarity = "Rare",
			Price = 6500,
			MoneyPerSecond = 50,

			Icon = "rbxassetid://82315294362133",

			IdleAnimation = "rbxassetid://507766666",
			WalkAnimation = "rbxassetid://10921244891",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://78526440404062"
		},
		
		["Beefchoplets"] = {
			Rarity = "Rare",
			Price = 7500,
			MoneyPerSecond = 55,

			Icon = "rbxassetid://139786325902163",

			IdleAnimation = "rbxassetid://507766666",
			WalkAnimation = "rbxassetid://507777826",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://126762249931128"
		},
		
		["OsterDog"] = {
			Rarity = "Rare",
			Price = 9000,
			MoneyPerSecond = 65,

			Icon = "rbxassetid://120573470283583",

			IdleAnimation = "rbxassetid://507766666",
			WalkAnimation = "rbxassetid://507777826",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://95540446187026"
		},
		
		["Taymaster"] = {
			Rarity = "Epic",
			Price = 10000,
			MoneyPerSecond = 75,

			Icon = "rbxassetid://72514095823099",

			IdleAnimation = "rbxassetid://122257458498464",
			WalkAnimation = "rbxassetid://616122287",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://78028581344416"
		},	
		
		["UwuPyxl"] = {
			Rarity = "Epic",
			Price = 15000,
			MoneyPerSecond = 100,

			Icon = "rbxassetid://115137418114745",

			IdleAnimation = "rbxassetid://910004836",
			WalkAnimation = "rbxassetid://910034870",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://127377257915886"
		},
		
		["Protori"] = {
			Rarity = "Epic",
			Price = 20000,
			MoneyPerSecond = 130,

			Icon = "",

			IdleAnimation = "rbxassetid://110211186840347",
			WalkAnimation = "rbxassetid://83842218823011",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://135148049747326"
		},
		
		["MrWindy"] = {
			Rarity = "Epic",
			Price = 25000,
			MoneyPerSecond = 150,

			Icon = "rbxassetid://140014005346330",

			IdleAnimation = "rbxassetid://507766666",
			WalkAnimation = "rbxassetid://507777826",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://83965480355507"
		},
		
		["Amberrry"] = {
			Rarity = "Epic",
			Price = 30000,
			MoneyPerSecond = 175,

			Icon = "",

			IdleAnimation = "rbxassetid://16738333868",
			WalkAnimation = "rbxassetid://16738340646",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://105106818659800"
		},
		
		["Fierzaa"] = {
			Rarity = "Epic",
			Price = 35000,
			MoneyPerSecond = 200,

			Icon = "rbxassetid://103179907960193",

			IdleAnimation = "rbxassetid://656117400",
			WalkAnimation = "rbxassetid://656118852",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://79681289271069"
		},
		
		["RoyStanford"] = {
			Rarity = "Epic",
			Price = 40000,
			MoneyPerSecond = 250,

			Icon = "rbxassetid://139103921866610",

			IdleAnimation = "rbxassetid://507766666",
			WalkAnimation = "rbxassetid://507777826",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://97033675499463"
		},			
		
		["Defaultio"] = {
			Rarity = "Legendary",
			Price = 50000,
			MoneyPerSecond = 300,

			Icon = "rbxassetid://123639549135898",

			IdleAnimation = "rbxassetid://845397899",
			WalkAnimation = "rbxassetid://2510202577",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://95560389930766"
		},	
		
		["SnickTrix"] = {
			Rarity = "Legendary",
			Price = 100000,
			MoneyPerSecond = 500,

			Icon = "rbxassetid://122434693606737",

			IdleAnimation = "rbxassetid://507766666",
			WalkAnimation = "rbxassetid://507777826",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://111167614679518"
		},
		
		["FireAtacck"] = {
			Rarity = "Legendary",
			Price = 150000,
			MoneyPerSecond = 650,

			Icon = "",

			IdleAnimation = "rbxassetid://4417977954",
			WalkAnimation = "rbxassetid://2510202577",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://81581010705784"
		},	
		
		["Shawnyg"] = {
			Rarity = "Legendary",
			Price = 200000,
			MoneyPerSecond = 750,

			Icon = "rbxassetid://138033232986088",

			IdleAnimation = "rbxassetid://507766666",
			WalkAnimation = "rbxassetid://507777826",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://127145490431354"
		},
		
		["Chunchbunch"] = {
			Rarity = "Legendary",
			Price = 250000,
			MoneyPerSecond = 1000,

			Icon = "rbxassetid://126207841246644",

			IdleAnimation = "rbxassetid://2510197257",
			WalkAnimation = "rbxassetid://2510202577",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://75262256654418"
		},
	
		["LostInfinity"] = {
			Rarity = "Legendary",
			Price = 300000,
			MoneyPerSecond = 1300,

			Icon = "rbxassetid://72675471859483",

			IdleAnimation = "rbxassetid://507766666",
			WalkAnimation = "rbxassetid://507777826",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://71778113934854"
		},	
		
		["dbs_johnny"] = {
			Rarity = "Legendary",
			Price = 350000,
			MoneyPerSecond = 1600,

			Icon = "",

			IdleAnimation = "rbxassetid://507766666",
			WalkAnimation = "rbxassetid://507777826",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://82027048903593"
		},	
		
		["Benoxa"] = {
			Rarity = "Mythic",
			Price = 400000,
			MoneyPerSecond = 2000,

			Icon = "rbxassetid://105947177784931",

			IdleAnimation = "rbxassetid://507766666",
			WalkAnimation = "rbxassetid://2510202577",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://128822513361079"
		},
		
		["Nosniy"] = {
			Rarity = "Mythic",
			Price = 500000,
			MoneyPerSecond = 2500,

			Icon = "rbxassetid://126272606189789",

			IdleAnimation = "rbxassetid://507766666",
			WalkAnimation = "rbxassetid://616163682",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://108184602963806"
		},
		
		["Chillthrill709"] = {
			Rarity = "Mythic",
			Price = 1000000,
			MoneyPerSecond = 5000,

			Icon = "rbxassetid://74892010733697",

			IdleAnimation = "rbxassetid://507766666",
			WalkAnimation = "rbxassetid://507777826",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://76846624635256"
		},
		
		["Dued1"] = {
			Rarity = "Mythic",
			Price = 1500000,
			MoneyPerSecond = 7500,

			Icon = "rbxassetid://109478717704708",

			IdleAnimation = "rbxassetid://507766666",
			WalkAnimation = "rbxassetid://507777826",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://89542797459478"
		},
		
		["YGvw_Sol"] = {
			Rarity = "Mythic",
			Price = 2000000,
			MoneyPerSecond = 10000,

			Icon = "rbxassetid://110841327607507",

			IdleAnimation = "rbxassetid://507766666",
			WalkAnimation = "rbxassetid://507777826",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://126137274397679"
		},
		
		["Aesthetical"] = {
			Rarity = "Mythic",
			Price = 4000000,
			MoneyPerSecond = 13500,

			Icon = "rbxassetid://120656564361815",

			IdleAnimation = "rbxassetid://507766666",
			WalkAnimation = "rbxassetid://507777826",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://123705956277289"
		},
		
		["0_0"] = {
			Rarity = "Developer God",
			Price = 5000000,
			MoneyPerSecond = 15000,

			Icon = "",

			IdleAnimation = "rbxassetid://742637544",
			WalkAnimation = "rbxassetid://742640026",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://103802200917348"
		},
		
		["DJMonopoli"] = {
			Rarity = "Developer God",
			Price = 7500000,
			MoneyPerSecond = 20000,

			Icon = "",

			IdleAnimation = "rbxassetid://2510197257",
			WalkAnimation = "rbxassetid://2510202577",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://81311399759097"
		},
		
		["Nikilis"] = {
			Rarity = "Developer God",
			Price = 8500000,
			MoneyPerSecond = 35000,

			Icon = "",

			IdleAnimation = "rbxassetid://507766666",
			WalkAnimation = "rbxassetid://507777826",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://124435295370310"
		},
		
		["Asimo3089"] = {
			Rarity = "Developer God",
			Price = 10000000,
			MoneyPerSecond = 50000,

			Icon = "",

			IdleAnimation = "rbxassetid://616136790",
			WalkAnimation = "rbxassetid://616122287",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://129770249284743"
		},
		
		["itsMuneeeb"] = {
			Rarity = "Developer God",
			Price = 15000000,
			MoneyPerSecond = 75000,

			Icon = "",

			IdleAnimation = "rbxassetid://782845736",
			WalkAnimation = "rbxassetid://656118852",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://130806486606189"
		},
		
		["BelowNatural"] = {
			Rarity = "Developer God",
			Price = 25000000,
			MoneyPerSecond = 100000,

			Icon = "",

			IdleAnimation = "rbxassetid://1083195517",
			WalkAnimation = "rbxassetid://782843345",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://139426878464821"
		},
		
		["No1_Preston"] = {
			Rarity = "Developer God",
			Price = 35000000,
			MoneyPerSecond = 200000,

			Icon = "",

			IdleAnimation = "rbxassetid://507766666",
			WalkAnimation = "rbxassetid://507777826",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://87285948682334"
		},
		
		["do_small"] = {
			Rarity = "Developer God",
			Price = 40000000,
			MoneyPerSecond = 275000,

			Icon = "",

			IdleAnimation = "rbxassetid://507766666",
			WalkAnimation = "rbxassetid://507777826",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://81516382657796"
		},
		
		["do_big"] = {
			Rarity = "Developer God",
			Price = 45000000,
			MoneyPerSecond = 350000,

			Icon = "",

			IdleAnimation = "rbxassetid://507766666",
			WalkAnimation = "rbxassetid://507777826",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://135579220353136"
		},
		
		["Cracky4"] = {
			Rarity = "Secret",
			Price = 50000000,
			MoneyPerSecond = 400000,

			Icon = "",

			IdleAnimation = "rbxassetid://891621366",
			WalkAnimation = "rbxassetid://656118852",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://79678932537642"
		},
		
		["Mygame43"] = {
			Rarity = "Secret",
			Price = 100000000,
			MoneyPerSecond = 500000,

			Icon = "",

			IdleAnimation = "rbxassetid://507766666",
			WalkAnimation = "rbxassetid://507777826",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://117066455809232"
		},
		
		["Rip_indra"] = {
			Rarity = "Secret",
			Price = 250000000,
			MoneyPerSecond = 1000000,

			Icon = "",

			IdleAnimation = "rbxassetid://507766666",
			WalkAnimation = "rbxassetid://507777826",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://78678712695463"
		},
		
		["Lightning_Splash"] = {
			Rarity = "Secret",
			Price = 500000000,
			MoneyPerSecond = 5000000,

			Icon = "",

			IdleAnimation = "rbxassetid://507766666",
			WalkAnimation = "rbxassetid://616146177",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://92922726996706"
		},
		
		["Jandel"] = {
			Rarity = "Secret",
			Price = 1000000000,
			MoneyPerSecond = 10000000,

			Icon = "",

			IdleAnimation = "rbxassetid://2510197257",
			WalkAnimation = "rbxassetid://2510202577",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://98417793909636"
		},
		
		["SpyderSammy"] = {
			Rarity = "Secret",
			Price = 2500000000,
			MoneyPerSecond = 15000000,

			Icon = "",

			IdleAnimation = "rbxassetid://507766666",
			WalkAnimation = "rbxassetid://507777826",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://113353740301389"
		},
		
		["Haz3mn"] = {
			Rarity = "Secret",
			Price = 5000000000,
			MoneyPerSecond = 35000000,

			Icon = "",

			IdleAnimation = "rbxassetid://782845736",
			WalkAnimation = "rbxassetid://782843345",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://124362226157175"
		},
		
		["MiniToon"] = {
			Rarity = "Secret",
			Price = 7500000000,
			MoneyPerSecond = 40000000,

			Icon = "",

			IdleAnimation = "rbxassetid://507766666",
			WalkAnimation = "rbxassetid://507777826",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://93213506177224"
		},
		
		["Stickmasterluke"] = {
			Rarity = "Secret",
			Price = 10000000000,
			MoneyPerSecond = 45000000,

			Icon = "",

			IdleAnimation = "rbxassetid://507766666",
			WalkAnimation = "rbxassetid://656118852",
			CarryAnimation = "rbxassetid://96104234604417",

			Sound = "rbxassetid://94860253070643"
		}
	}
}

return Things