local AssetIds = require(game.ReplicatedStorage.Configuration.Modules:WaitForChild("AssetIds"))
--[[

--------------| ABOUT RANKS |--------------

RANK	| DEFAULT NAME	| COMMANDS	| EXTRA DETAILS
-------------------------------------------------------------------------------------------------------------------
5		| Owner			| All		| Is automtically set. The Owner has full access to commands and features.
-------------------------------------------------------------------------------------------------------------------
4 		| HeadAdmin		| 1,2,3,4	| 
3 		| Admin			| 1,2,3		| 
2		| Mod			| 1,2		| Can only use commands on one person at a time. 
1 		| VIP			| 1			| Can only use commands on theirself.
-------------------------------------------------------------------------------------------------------------------
0		| NonAdmin		| 0			| The default rank. Players are limited to basic features.




--------------| SETUP RANKS |--------------																															 ]] return{


-- RANK, RANK NAMES & SPECIFIC USERS
Ranks = {
	{5,	"Owner",		};
	{4,	"Developer",	{"",0},	};
	{3,	"HeadAdmin",	{"",0},	};
	{2,	"Admin",		{"",0},	};
	{1,	"Mod",			{"",0},	};
	{0,	"NonAdmin",		};
};


-- GAMEPASSES
Gamepasses = {
	[AssetIds.GamePasses.HDAdmin] = "Admin";
};


-- ASSETS
Assets = {
	[0] = "Mod";
};


-- GROUPS
Groups = {
	[0] = {
		[254] = "Admin";
		[1] = "Mod";
		};
};


-- FRIENDS
Friends = "NonAdmin";


-- VIP SERVER OWNER
VipServerOwner = "NonAdmin";


-- FREE ADMIN
FreeAdmin = "NonAdmin";








--------------| BANLAND |--------------
Banned = {"",0};








--------------| SYSTEM SETTINGS |--------------
Prefix				= ";";			-- The character you use before every command (e.g. ';jump me').
SplitKey 			= " ";			-- The character inbetween command arguments (e.g. setting it to '/' would change ';jump me' to ';jump/me').
BatchKey 			= "";			-- The character inbetween batch commands (e.g. setting it to '|' would change ';jump me ;fire me ;smoke me' to ';jump me | ;fire me | ;smoke me'
QualifierBatchKey 	= ",";			-- The character used to split up qualifiers (e.g. ;jump player1,player2,player3)

AppFont				= Enum.Font.SourceSans; -- You can also do "rbxasset://fonts/families/Bangers.json" or "Bangers"; 
AppTheme			= "Blurple";	-- The default UI theme.
AppThemes = {
	{"Blurple", Color3.fromRGB(94, 86, 213),	};
	{"Red", 	Color3.fromRGB(199, 80, 82),	};
	{"Orange", 	Color3.fromRGB(152, 114, 69),	};
	{"Green", 	Color3.fromRGB(73, 148, 104),	};
	{"Blue", 	Color3.fromRGB(91, 122, 189),	};
	{"Pink",	Color3.fromRGB(172, 121, 167),	};
	{"Black", 	Color3.fromRGB(35, 39, 47),		};
};

ShowOnlyUsableAndBuyableCommands	= true; 	-- Only display commands equal to or below the user's rank on the Commands page OR commands from Ranks or Roles they can purchase.
DisableBoosterBundles				= true;	-- This disables the Booster bundles. Please keep enabled to support the development of HD Admin.
RankRequiredToViewCommandsIcon		= 1; 		-- Minimum rank to view the icon which opens the Commands-Only page. This is hidden if the user can view the dashboard.
RankRequiredToViewDashboardIcon		= 1; 		-- Minimum rank to view the icon which opens the Dashboard

NoticeSoundId		= 2865227271;	-- The SoundId for notices.
NoticeVolume		= 0.1;			-- The Volume for notices.
NoticePitch			= 1;			-- The Pitch/PlaybackSpeed for notices.
ErrorSoundId		= 2865228021;	-- The SoundId for error notifications.
ErrorVolume			= 0.1;			-- The Volume for error notifications.
ErrorPitch			= 1;			-- The Pitch/PlaybackSpeed for error notifications.
AlertSoundId		= 9161622880;	-- The SoundId for alerts.
AlertVolume			= 0.5;			-- The Volume for alerts.
AlertPitch			= 1;			-- The Pitch/PlaybackSpeed for alerts.

WelcomeBadgeId		= 0;			-- Award new players a badge, such as 'Welcome to the game!'. Set to 0 for no badge.

CommandDebounce		= true;			-- Wait until the command effect is over to use again. Helps to limit abuse & lag. Set to 'false' to disable.
SaveRank			= true;			-- Saves a player's rank in the server they received it. (e.g. ;rank plrName rank). Use ';permRank plrName rank' to permanently save a rank. Set to 'false' to disable.
LoopCommands		= 3;			-- The minimum rank required to use LoopCommands.

Colors = {							-- The colours for ChatColors and command arguments. | Format: {"ShortName", "FullName", Color3Value};
	{"r", 		"Red",		 		Color3.fromRGB(255, 0, 0)		};
	{"o", 		"Orange",	 		Color3.fromRGB(250, 100, 0)		};
	{"y", 		"Yellow",			Color3.fromRGB(255, 255, 0)		};
	{"g", 		"Green"	,			Color3.fromRGB(0, 255, 0)		};
	{"dg", 		"DarkGreen"	, 		Color3.fromRGB(0, 125, 0)		};
	{"b", 		"Blue",		 		Color3.fromRGB(0, 255, 255)		};
	{"db", 		"DarkBlue",			Color3.fromRGB(0, 50, 255)		};
	{"p", 		"Purple",	 		Color3.fromRGB(150, 0, 255)		};
	{"pk",		"Pink",		 		Color3.fromRGB(255, 85, 185)	};
	{"bk",		"Black",		 	Color3.fromRGB(0, 0, 0)			};
	{"w",		"White",	 		Color3.fromRGB(255, 255, 255)	};
};

Cmdbar						= 1;			-- The minimum rank required to use the Cmdbar.
Cmdbar2						= 3;			-- The minimum rank required to use the Cmdbar2.
ViewBanland					= 3;			-- The minimum rank required to view the banland.
RankRequiredToViewPage		= {				-- || The pages on the main menu ||
	["Commands"]		= 1;
	["Moderation"]		= 3;
	["Revenue"]			= 4;
	["Settings"]		= 1;
};

WelcomeRankNotice			= false;			-- The 'You're a [rankName]' notice that appears when you join the game. Set to false to disable.
ChartsNotice				= false;			-- The 'enable HttpService to be added to the HD Admin Charts' notice sent to the owner of the game
WarnIncorrectPrefix			= true;			-- Warn the user if using the wrong prefix | "Invalid prefix! Try using [correctPrefix][commandName] instead!"
DisableAllNotices			= false;		-- Set to true to disable all HD Admin notices.
HideWarningsIfBelowRank		= 1; 			-- Hide core notices such as 'CommandName is not a valid command!' and 'You do not have permission to use this command' for ranks below the specified rank

ScaleLimit					= 3;			-- The maximum size players with a rank lower than 'IgnoreScaleLimit' can scale theirself. For example, players will be limited to ;size me 4 (if limit is 4) - any number above is blocked.
IgnoreScaleLimit			= 3;			-- Any ranks equal or above this value will ignore 'ScaleLimit'
CommandLimits				= {				-- Enables you to set limits for commands which have a number argument. Ranks equal to or higher than 'IgnoreLimit' will not be affected by Limit.
	["spin"]	= {
		Limit 				= 10;
		IgnoreLimit 		= 3;
	}; 
	["headSize"] = {
		Limit 				= 3;
		IgnoreLimit 		= 3;
	}; 
	["height"]	= {
		Limit 				= 2;
		IgnoreLimit 		= 3;
	}; 
};

VIPServerCommandBlacklist	= {"permRank", "permBan", "globalAnnouncement"};	-- Commands players are probihited from using in VIP Servers.
GearBlacklist				= {};	-- The IDs of gear items to block when using the ;gear command.
IgnoreGearBlacklist			= 4;			-- The minimum rank required to ignore the gear blacklist.

PlayerDataStoreVersion		= "V1.0";		-- Data about the player (i.e. permRanks, custom settings, etc). Changing the Version name will reset all PlayerData.
SystemDataStoreVersion		= "V1.0";		-- Data about the game (i.e. the banland, universal message system, etc). Changing the Version name will reset all SystemData.

CoreNotices					= {				-- Modify core notices. You can find a table of all CoreNotices under [MainModule > Client > SharedModules > CoreNotices]
	--NoticeName = NoticeDetails;
};

AutoSaveMap					= false;		 -- Should the whole game be backed up automatically on start? If false, you'll have to call :SaveMap() first before :LoadMap()



--------------| MODIFY COMMANDS |--------------
SetCommandRankByName = {
		["emotes"] = "HeadAdmin";	
		["emote"] = "HeadAdmin";	
		["phase"] = "HeadAdmin";	
		["ice"] = "HeadAdmin";	
		["jail"] = "HeadAdmin";	
		["invisible"] = "HeadAdmin";
		["material"] = "HeadAdmin";	
		["reflectance"] = "HeadAdmin";	
		["transparency"] = "HeadAdmin";
		["laserEyes"] = "HeadAdmin";	
		["refresh"] = "HeadAdmin";	
		["respawn"] = "HeadAdmin";
		["warp"] = "HeadAdmin";	
		["blur"] = "HeadAdmin";	
		["hideGuis"] = "HeadAdmin";
		["showGuis"] = "HeadAdmin";	
		["freeze"] = "HeadAdmin";	
		["name"] = "HeadAdmin";
		["hideName"] = "HeadAdmin";	
		["depth"] = "HeadAdmin";	
		["hipHeight"] = "HeadAdmin";
		["morph"] = "HeadAdmin";	
		["bundle"] = "HeadAdmin";	
		["forcefield"] = "HeadAdmin";
		["h"] = "HeadAdmin";	
		["hr"] = "HeadAdmin";	
		["ho"] = "HeadAdmin";
		["hy"] = "HeadAdmin";	
		["hg"] = "HeadAdmin";	
		["hdg"] = "HeadAdmin";	
		["hb"] = "HeadAdmin";	
		["hdb"] = "HeadAdmin";	
		["hp"] = "HeadAdmin";	
		["hpk"] = "HeadAdmin";
		["hbk"] = "HeadAdmin";	
		["fly"] = "HeadAdmin";	
		["fly2"] = "HeadAdmin";
		["noclip"] = "HeadAdmin";	
		["noclip2"] = "HeadAdmin";	
		["speed"] = "HeadAdmin";
		["fast"] = "HeadAdmin";	
		["slow"] = "HeadAdmin";	
		["jumpHeight"] = "HeadAdmin";
		["superJump"] = "HeadAdmin";	
		["jumpPower"] = "HeadAdmin";	
		["heavyJump"] = "HeadAdmin";
		["health"] = "HeadAdmin";	
		["god"] = "HeadAdmin";	
		["damage"] = "HeadAdmin";
		["kill"] = "HeadAdmin";	
		["teleport"] = "HeadAdmin";	
		["bring"] = "HeadAdmin";
		["to"] = "HeadAdmin";	
		["apparate"] = "HeadAdmin";	
		["handTo"] = "HeadAdmin";
		["give"] = "HeadAdmin";
		["sword"] = "HeadAdmin";	
		["gear"] = "HeadAdmin";	
		["explode"] = "HeadAdmin";
		["title"] = "HeadAdmin";	
		["titler"] = "HeadAdmin";	
		["titleo"] = "HeadAdmin";
		["titley"] = "HeadAdmin";	
		["titleg"] = "HeadAdmin";	
		["titledg"] = "HeadAdmin";	
		["titleb"] = "HeadAdmin";	
		["titledb"] = "HeadAdmin";	
		["titlep"] = "HeadAdmin";	
		["titlepk"] = "HeadAdmin";
		["titlebk"] = "HeadAdmin";	
		["fling"] = "HeadAdmin";	
		["r15"] = "HeadAdmin";
		["r6"] = "HeadAdmin";	
		["width"] = "HeadAdmin";	
		["view"] = "Admin";	
		["char"] = "Admin";	
		["shirt"] = "Admin";	
		["pants"] = "Admin";	
		["hat"] = "Admin";	
		["clearhats"] = "Admin";	
		["face"] = "Admin";
		["head"] = "Admin";	
		["headSize"] = "Admin";	
		["squash"] = "Admin";
		["bighead"] = "Admin";	
		["ghost"] = "Admin";	
};	








};